### ISSUE TITLE
Licence?

### ISSUE THREAD

**Issue by lovesh** [infincia/bip39-rs#12]
What is the licence for this project?. The [toml](https://github.com/infincia/bip39-rs/blob/master/Cargo.toml) file says MIT/Apache but there is no LICENCE file.

**Comment by steveatinfincia** [comment]
Hi :D 

Yes it's dual licensed as MIT/Apache 2.0, I've pushed license files into the repository and published a new minor version `v0.5.1` since the license files are included in cargo packages.

**Comment by lovesh** [comment]
Thanks
