### ISSUE TITLE
Documentations Link in ReadMe goes to outdated version

### ISSUE THREAD

**Issue by josh-kean** [infincia/bip39-rs#27]
I noticed that when you click in the documentation you get taken to the instructions for version 0.5.1, which has examples that aren't in compliance with the most up to date version of this crate.
Since the actual link being used is https://docs.rs/bip39, I think this problem is with docs.rs, and nothing in the actual repository.

**Comment by wigy-opensource-developer** [comment]
0.6 was never released. There has been a fork of this project going on as https://crates.io/crates/tiny-bip39 though.
